### ISSUE TITLE
https://github.com/rubygems/rubygems/issues/5289

### ISSUE THREAD

**Issue by uhuntu** [svenfuchs/gem-release#105]
Hello there, can some one help to explain this: https://github.com/rubygems/rubygems/issues/5289

It is pretty strange.

I had followed this line: https://bundler.io/guides/creating_gem.html to start the scratch the gem making, but lastly he said you should install a plugin to bump release, then I follow, after that strange thing happen.
```
-> % bundle exec rake release
foodie_hunt 1.1.1 built to pkg/foodie_hunt-1.1.1.gem.
Tag v1.1.1 has already been created.
Error loading RubyGems plugin "/usr/share/rvm/gems/ruby-3.1.2/plugins/gem-release_plugin.rb": cannot load such file -- gem/release (LoadError)
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please bump the version number and push a new different release.
See also `gem yank` if you want to unpublish the bad release.
```

You can see that there is a line: 
```
Error loading RubyGems plugin "/usr/share/rvm/gems/ruby-3.1.2/plugins/gem-release_plugin.rb": cannot load such file -- gem/release (LoadError)
```

Then I used the google machine to reach how it is happening, the I found here: https://github.com/rubygems/rubygems/issues/5289
Some ones also were struggling on this issue.

**Comment by PikachuEXE** [comment]
Try this first?
https://github.com/rubygems/rubygems/issues/5289#issuecomment-1295884790

**Comment by uhuntu** [comment]
Yeah you are smart.

**Comment by pboling** [comment]
@svenfuchs I think this should be reopened.  It is a legitimate bug.

Lots of plugins use the gem `gem-release`, which isn't part of bundler / rubygems, but appears to conflict in load paths, resulting in this error.

If you use a global Ruby for multiple projects (as you often do with any type of ruby version manager), some gems or apps will depend on the `gem-release`, while other won't, and thus it will be installed and within reach of `gem`'s load paths.

Then when you do a canonical `bundle exec rake release` using the standard gem tasks, in a project that does not depend on `gem-release`, but within a Ruby environment that has it installed, it will mistakenly hit that load path.

You can see that is exactly what happened in the paths @jrochkind had:
```
/Users/jrochkind/.gem/ruby/3.0.4/gems/gem-release-2.2.2/lib/rubygems_plugin.rb
```

I just had the same issue.  I am not sure which library depended on it, but there are 2 temporary solutions

1. Add as a dependency: `bundle add gem-release`
2. Uninstall globally from Ruby:`gem uninstall gem-release`

**Comment by jrochkind** [comment]
Oh interesting. I don't expect gems that are installed systemwide but NOT in my bundle to affect my bundle, since Bundler is normally so good about that. That's unfortunate.

**Comment by tvdeyen** [comment]
I can validate this is fixed by #111 and

```
gem install gem-release -v '2.2.3.alpha4'
```

**Comment by pboling** [comment]
@jrochkind The solution, for all Ruby gem libraries, is to use `require_relative` to load internal `lib` files.

See https://github.com/rubocop/rubocop/issues/8748#issuecomment-2363327346

**Comment by jrochkind** [comment]
@pboling interesting, I think that's definitely not yet widely known! i have written many gems that don't do that, unfortunately. 

If someone wanted to write up this guidance with clear explanation of motivation/why (I am not entirely following myself), that would def be a service to the community!  If such already exists somewehre that is great! Perhaps it should be on some kind of "official" site somewhere to have credibility and attention.

**Comment by pboling** [comment]
I plan to work on that, somewhere on my todo list ![image](https://github.com/user-attachments/assets/23a918ab-e775-40cf-aaee-c243f96440be)

**Comment by PikachuEXE** [comment]
Fix released in https://rubygems.org/gems/gem-release/versions/2.2.3
