### ISSUE TITLE
Prompt for confirmation before releasing gems

### ISSUE THREAD

**Issue by dgeb** [svenfuchs/gem-release#22]
As discussed in #15, we should add a prompt to `gem release` (and `gem bump --release`) for confirmation before pushing both public and private gems.

For instance, `Release version 1.0.1 of public_gem to rubygems.org? (y / n)` or `Release version 1.0.0 of private_gem to http://rubygems.example.com? (y / n)`. Skip this prompt with the `--quiet` / `-q` option.

**Comment by svenfuchs** [comment]
Yes, true. I think we can close this (6 years later) 

😄 

Please reopen if I'm mistaken.
