### ISSUE TITLE
could you make pushing to origin optional

### ISSUE THREAD

**Issue by gizmomogwai** [svenfuchs/gem-release#26]
i have some gems that are "managed" by repo and i would prefer to just push the tags with repo

**Comment by svenfuchs** [comment]
@gizmomogwai Do you still have this issue? If so, could you reopen this here, and let me know which command you were using? In case you remember 5 years later :)

I believe `2.0.0.pre.1` should address this issue though. It gives you more control over various options. See https://github.com/svenfuchs/gem-release/pull/64
