### ISSUE TITLE
When command are combined, the .gemrelease file is ignored

### ISSUE THREAD

**Issue by hdoedens** [svenfuchs/gem-release#49]
When a .gemrelease file is created with, for example, a host for release:

```

---
release:
  host: 'http://foo.bar'
```

The file is picked up when issueing `gem release` but the file is ignored when combining the release command with another command `gem bump --version 1.1.3 --release`

**Comment by svenfuchs** [comment]
Thanks for the report, @hdoedens. 

I believe this issue should be addressed in `2.0.0.pre.1`, see https://github.com/svenfuchs/gem-release/pull/64

Specifically, there's now more flexibility in configuring gem-release. And things are tested better. See https://github.com/svenfuchs/gem-release/tree/sf-v2#configuration for configuration options.

I believe in your case it should be sufficient to use:

```
# top level keys, apply to all commands
host: http://foo.bar
```

or

```
export GEM_RELEASE_HOST=http://foo.host/private
```

I am going to close this here, please reopen, and let me know if things do not work as expected.
