### ISSUE TITLE
`gem bump` work with "*_rb" suffix

### ISSUE THREAD

**Issue by jbodah** [svenfuchs/gem-release#52]
We've been writing some gems that need to have "*_rb" at the end for the gem name

Ex.

```
# gem name is task_rb
lib/task/version.rb
```

It would be great if `gem bump` worked on this as well

**Comment by svenfuchs** [comment]
I believe this was implemented in your PR https://github.com/svenfuchs/gem-release/pull/53, and has now been ported to `v2` in https://github.com/svenfuchs/gem-release/pull/64/commits/4dff9f18ff1d93b9a46b90a4de4a99a8a9b04ea9

Closing this here for now. Please let me know if I'm mistaken!
