### ISSUE TITLE
Make --quiet a global flag / flag supported by all commands

### ISSUE THREAD

**Issue by jabbrwcky** [svenfuchs/gem-release#56]
Hi,

it would be nice to have the --quiet flag for all subcommands. I currently use gem bump in a filter script for git-flow and it is a real pain to catch all output by gem bump to make sure that the filter just returns the version to use for the release.

**Comment by svenfuchs** [comment]
Thanks for the report, @jabbrwcky , and sorry for not following up on this earlier.

I believe your issue should be addressed in `2.0.0.pre.1`, see https://github.com/svenfuchs/gem-release/pull/64

Specifically, there's now more flexibility in configuring gem-release. And things are tested better. See https://github.com/svenfuchs/gem-release/tree/sf-v2#configuration for configuration options.

I believe in your case it should be sufficient to use:

```
# top level keys, apply to all commands
quiet: true
```

or

```
export GEM_RELEASE_QUIET=true
```

I am going to close this here. Please let me know if things do not work as expected.
