### ISSUE TITLE
Issues with in-repo gems

### ISSUE THREAD

**Issue by mwpastore** [svenfuchs/gem-release#58]
I have a RubyGem with another RubyGem in-repo (directly, not a submodule). The file structure looks something like:

- sinja/
  - .git/
  - Gemfile
  - lib/sinja/version.rb
  - sinja.gemspec
  - extensions/sequel/
    - Gemfile
    - lib/sinja/sequel/version.rb
    - sinja-sequel.gemspec

The gemspecs look normal, i.e. like they would if they were in separate repos. In the two Gemfiles, after the `gemspec` directive, I'm using the `:path` option to point to the relative directories for development. So something like:

```ruby
# sinja/Gemfile
gemspec
gem 'sinja-sequel', :require=>false, :path=>'extensions/sequel'
```

```ruby
# sinja/sinja.gemspec
spec.add_development_dependency 'sinja-sequel', '~> 0.1'
```

```ruby
# sinja/extensions/sequel/Gemfile
gemspec
gem 'sinja', :require=>false, :path=>'../..' 
```

```ruby
# sinja/extensions/sequel/sinja-sequel.gemspec
spec.add_dependency 'sinja', '>= 1.2.0.pre2', '< 2'
```

Here's the scoop:

* `bundle install|update|exec` works fine in both gemspec directories
* `gem build|push` works fine in both gemspec directories
* `gem bump` finds `sinja/extensions/sequel/lib/sinja/sequel/version.rb` first and uses it as the base version for both gems, updating both `version.rb` files to the new version (PROBLEM 1)
* `gem release` works fine in `sinja/extensions/sequel/`
* `gem release` in `sinja/` finds `sinja/extensions/sequel/sinja-sequel.gemspec` first and tries to re-release it (PROBLEM 2)
* `gem release sinja.gemspec` emits `ERROR:  Gemspec file not found: sinja.gemspec` (PROBLEM 3)

PROBLEM 1: How can I restrict `gem bump` to only work on one or the other `version.rb` file at a time?

PROBLEM 2: Why doesn't `gem release` in the top-level directory find the top-level gemspec?

PROBLEM 3: What in the blazes is going on here?

**Comment by svenfuchs** [comment]
Hey @mwpastore 

Sorry for not getting back to you earlier. 

I believe your case is covered in [this rewrite](https://github.com/svenfuchs/gem-release/issues/64) ... see https://github.com/svenfuchs/gem-release/blob/sf-v2/scenarios/04-nested_gem_conventional_dirname.md and https://github.com/svenfuchs/gem-release/blob/sf-v2/scenarios/05-nested_gem_irregular_dirname.md. 

I have used your usecase as an example for these two.

**Comment by mwpastore** [comment]
Fantastic! I moved away from this directory structure due to this issue and others (with Bundler and Gemnasium, to name two), so I can't confirm the fix, but I'll reconsider it for other projects in the future.
