### ISSUE TITLE
Get current version of gem or next-version on STDOUT?

### ISSUE THREAD

**Issue by gepandz** [svenfuchs/gem-release#71]
Neat gem; I like it a lot.

Is there a way to get the current version without having to `grep` or `sed` lib/my_gem/version.rb? I'd like to have a task in a Rakefile to create a git branch with the name of the version, similar to your `gem tag` command, but I'm having trouble figuring out the right incantations. Alternatively, being able to get the "bumped" new version as just a plain text-string on STDOUT would let me mess with it on my own, like a stripped-down `--pretend`.

These are probably more enhancement requests than Issues...

Thanks for the good work! :-)

**Comment by svenfuchs** [comment]
Thanks for the suggestion, @gepandz! I like this.

One idea would be to allow for `gem bump -v minor --branch` which (assuming the current version is `1.0.0`) would check out a branch `v1.0.1` and commit to it (unless `--no-commit` is given). This would solve your usecase without having to fiddle with a custom Rake task, wouldn't it? How do you usually name such branches?

One complication here is that `gem bump` is supposed to work with several gems contained in a directory. So we could have `lib/gem-1/version.rb` and `lib/gem-2/version.rb` be at two different versions. I'm not quite sure what a good behavior would be in this case.

I also like the idea of having `--pretend` detect if `$stdout.tty?` (or something) is `false` and output something more parsable/awk friendly.

**Comment by svenfuchs** [comment]
Pushed a bunch of changes that make it respect `tty?` so that:

```
# with a tty
$ gem bump --pretend

Bumping gem-release from version 2.0.0.dev.5 to 2.0.0.dev.6
Staging lib/gem/release/version.rb
$ git add lib/gem/release/version.rb

Creating commit
$ git commit -m "Bump gem-release to 2.0.0.dev.6"

All is good, thanks my friend.

# without a tty
$ gem bump --pretend | cat
bump gem-release 2.0.0.dev.5 2.0.0.dev.6
git_add lib/gem/release/version.rb
git_commit "Bump gem-release to 2.0.0.dev.6"

# so that it is easy to grep/awk the target version number:
$ gem bump --pretend | grep bump | awk '{ print $4 }'
2.0.0.dev.6
```

**Comment by svenfuchs** [comment]
Also added `gem bump --branch` to checkout a branch before bumping the version and commiting:

```
# without a branch name
$ gem bump --branch --pretend

Checking out branch v2.0.0.dev.6
$ git checkout -b v2.0.0.dev.6

Bumping gem-release from version 2.0.0.dev.5 to 2.0.0.dev.6
Staging lib/gem/release/version.rb
$ git add lib/gem/release/version.rb

Creating commit

$ git commit -m "Bump gem-release to 2.0.0.dev.6"

All is good, thanks my friend.


# with a branch name
$ gem bump --branch foo --pretend

Checking out branch foo
$ git checkout -b foo

Bumping gem-release from version 2.0.0.dev.5 to 2.0.0.dev.6
Staging lib/gem/release/version.rb
$ git add lib/gem/release/version.rb

Creating commit
$ git commit -m "Bump gem-release to 2.0.0.dev.6"

All is good, thanks my friend.


# skip the commit
$ gem bump --branch --no-commit --pretend

Checking out branch v2.0.0.dev.6
$ git checkout -b v2.0.0.dev.6

Bumping gem-release from version 2.0.0.dev.5 to 2.0.0.dev.6
All is good, thanks my friend.
```

**Comment by svenfuchs** [comment]
I'm going to close this for now. Please re-open if I got the usecase wrong.

Thanks again!
