### ISSUE TITLE
Can't see 2.0.1 on Github?

### ISSUE THREAD

**Issue by PikachuEXE** [svenfuchs/gem-release#74]

**Comment by svenfuchs** [comment]
@PikachuEXE sorry about that, forgot to push the tag. it's now there. `2.0.1` is the same as `2.0.0.rc.3` ... `2.0.0` was yanked.

**Comment by pboling** [comment]
@svenfuchs You know... There is a gem that can bump, tag, push tag, and release all in one command... 💃 Trying to remember what it is called.
