### ISSUE TITLE
Bumping `major` and `minor` does not work.

### ISSUE THREAD

**Issue by edisonywh** [svenfuchs/gem-release#81]
<img width="514" alt="06-18-903PM" src="https://user-images.githubusercontent.com/20277437/59684452-9b0b9080-920c-11e9-85a5-d2eae31e4b65.png">

<img width="502" alt="06-18-903PM-1" src="https://user-images.githubusercontent.com/20277437/59684456-9cd55400-920c-11e9-8007-edaa66e406f2.png">

As you can see from the command, I ran both `minor` and `major` but the gem only increments the `patch`.

## Note:

`gem bump --version 0.3.0` works fine though

**Comment by PikachuEXE** [comment]
The command argument/option is changed a bit:
`gem bump behaves --version minor --pretend`
`gem bump behaves --version major --pretend`

Check the doc for option description:
https://github.com/svenfuchs/gem-release#options-1

![image](https://user-images.githubusercontent.com/1018543/60154851-360ef680-981b-11e9-9092-ad7ae0459904.png)

Let me know if
