### ISSUE TITLE
Automatic changelog?

### ISSUE THREAD

**Issue by danielwestendorf** [svenfuchs/gem-release#85]
I've been using this gem for a number of projects and really appreciate the work that has gone into it. ❤️ 

When generating a release, I wonder if it would be possible to also update the changelog listed in the gemspec since the last tag. Maybe in an interactive fashion, allowing the user to select, comment, and link to the commits?

I'd be willing to put some effort into this if the idea aligns with the project.

**Comment by PikachuEXE** [comment]
`update the changelog listed in the gemspec since the last tag`
I don't quite understand this part
What commands do you usually run on "creating a release"?

**Comment by danielwestendorf** [comment]
> update the changelog listed in the gemspec since the last tag

If you create a new gem, the gemspec automatically generates a [changelog_uri](https://github.com/hoalife/hoalife-ruby/blob/master/hoalife.gemspec#L20). 

This is important to me because services like dependabot add the changelog to the PR.

I typically run `gem bump --tag --push`.

I've [found something](https://github.com/git-chglog/git-chglog) (with a tweak)[https://github.com/git-chglog/git-chglog/issues/28#issuecomment-462165811 ] that actually does the changelog generation for me, but I don't know if it'll work well with this gem yet.

**Comment by PikachuEXE** [comment]
Normally I update the version in file & Change log myself, commit and run
`gem release --tag --push`

I think change log auto update should be handled by another library
Plus you can update it before/after releasing a new version
