### ISSUE TITLE
Match rubygems not-quite-Semver versioning for pre-release versioning

### ISSUE THREAD

**Issue by pnomolos** [svenfuchs/gem-release#86]
Unfortunately, rubygems requires a `.` separator instead of a `-` for pre-release gems.  Would it be possible to update gem-release to comply with that constraint?

Ex. `"0.169.0"` should `gem bump -v pre` to `"0.170.0.pre.1"` instead of `"0.170.0-pre.1"`

See https://github.com/rubygems/rubygems/issues/592#issuecomment-328520725 and the offending line that causes all the issues: https://github.com/rubygems/rubygems/blob/064cfaf7f5357c16a4fae04d53587fcf69b6df3f/lib/rubygems/version.rb#L219

**Comment by PikachuEXE** [comment]
@pnomolos 
Please take a look at #87 at see if there is any problem
You can also try to test with it locally

**Comment by PikachuEXE** [comment]
@pnomolos 
I won't release #87 unless you test it ;)

**Comment by pnomolos** [comment]
Hah fair enough!  I’ll try and get to it this week.

**Comment by PikachuEXE** [comment]
@pnomolos 
The sooner you finished testing the sooner I can release it~
