### ISSUE TITLE
Does `gem release` support MFA?

### ISSUE THREAD

**Issue by cben** [svenfuchs/gem-release#88]
Hi, this is probably not problem in `gem release`, opening anyway as maybe it will help others troubleshooting.

I've tried enabling multi-factor authentication in rubygems.org at "UI and API".
This should make `gem push` prompt for an OTP code:
https://guides.rubygems.org/using-mfa-in-command-line/
But I didn't use `gem push` directly, I used `gem release` which it seems failed, without prompting me for an OTP code.  (Sorry, didn't save the output, laptop lost power since).

Is there any known limitation?  Are executed commands connected to stdin?

Alternatively, could add an `--otp` flag to be passed on to `gem push`, requiring no interaction.

**Hmm, possibly my `gem` CLI was old?**  I got via `rbenv install 2.5.6`; `gem --version` says 2.7.6.2, and it **doesn't support `--otp`, so I guess doesn't know how to prompt either.**  
Building ruby 2.6.4 gave me `gem` 3.0.3 which does support `--otp` so I guess could Just Work?  I'll confirm next time I make a release...

P.S. another workaround: `gem release` worked when I set my account MFA to "UI only" level.  This is weaker but better than nothing.

[additional search keywords: 2FA, OTP]

**Comment by PikachuEXE** [comment]
I have release a few of my own gems via `gem release` with 2FA enabled
I use latest iTerm, not sure if there is other limitations for your terminal/setup.
I will try to run `gem release` again on a test gem to see if there is a problem next week (on vacation now)

**Comment by PikachuEXE** [comment]
Just released `gem-release` with `gem release --tag --push` with 2FA

![image](https://user-images.githubusercontent.com/1018543/66547682-4fda0c80-eb72-11e9-9d69-793873586cac.png)
![image](https://user-images.githubusercontent.com/1018543/66547715-654f3680-eb72-11e9-901f-845400a1e78f.png)
