### ISSUE TITLE
Question: it there a way bump version in changelog file?

### ISSUE THREAD

**Issue by mainameiz** [svenfuchs/gem-release#89]
Hello.

First of all, thanks for making this gem. I was very glad when I have found it. :)

I have a question.
I want to use this gem and everything is fine. But in addition to existing functionality I also would to bump version in my changelog file.

E.g.

before
```diff
--- CHANGELOG.md	2019-10-11 13:00:11.095262564 +0300
+++ CHANGELOG.md	2019-10-11 13:00:12.455265870 +0300
@@ -1 +1,3 @@
 ## Unreleased
+
+## 0.3.1 - 2019-09-09

 Bugfixes:
  - fix 1 ...
  - fix 2

 ## 0.3.0 - 2019-09-01
```

Is there any way to do this? May be some way to hook into `bump` command somewhere between actual changing of `version.rb` file and making a commit.

For now I use a workaround... I write simple script which invokes `gem bump --no-commit --branch`, then I make changes in `CHANGELOG.md` and then I invoke `git add` and `git push` myself.

I will be glad to hear your thoughts.

**Comment by PikachuEXE** [comment]
There are many change log styles (even file names)
Some project even uses Github releases only
I think you should find tools to help you update change log instead of this gem

**Comment by mainameiz** [comment]
> There are many change log styles (even file names)

Definitely. I agree. I do not suggest to include the functionality of updating changelog files in the gem.

I just think about that the process of updating the version in changelog is similar to the process of updating the version in `version.rb`. So I imagine that this gem could help me with this. For example if the gem-release will include programmatic API to investigate the current version and to bump the `version.rb` I could write the following:

```ruby
#!/usr/bin/env ruby

FileUtils.chdir(project_root) do
  gem_release = Gem::Release.init(ARGV) # suppose ARGV = ['-v', 'minor']
  gem_release.create_branch
  gem_release.bump # bump version and write new version to file

  # my code tho change CHAGELOG file
  changelog = File.read('CHANGELOG.md')
  changelog.sub(/..../, "...#{gem_release.new_version}") # change version in changelog

  gem_release.git.add_files('CHANGELOG.md', gem_release.version_file_path)
  gem_release.commit
  gem.release.push
end
```

What do you think?

**Comment by PikachuEXE** [comment]
For me I just copy the new version from screen output and paste it on change log
I still write change log entries manually
