### ISSUE TITLE
Custom message template for bump throws error

### ISSUE THREAD

**Issue by Janani21** [svenfuchs/gem-release#90]
I am trying to provide a custom message for bumping version like 

`gem bump patch -m '<messge>'`

It throws below error 
```ERROR:  While executing gem ... (NoMethodError)
    undefined method `%' for true:TrueClass
```

**Comment by PikachuEXE** [comment]
Released as `2.1.1`

**Comment by Janani21** [comment]
Awesome. Thanks for the quick turnaround.
