### ISSUE TITLE
After a gem bump, is there any way to run bundler?

### ISSUE THREAD

**Issue by amalagaura** [svenfuchs/gem-release#93]
bundle will update the the new version in Gemfile.lock, otherwise after we push the commits we have local changes when we run gem release

I love this tool, but I am unable to use it because after a bump I have to push another commit which messes up the tagging.

**Comment by PikachuEXE** [comment]
I usually just gitignore Gemfile.lock
Or you can bump version without commit, run bundle, commit manually and run `gem release`

**Comment by amalagaura** [comment]
Thank you for your response.

I have read different things on the `Gemfile.lock` and thought the best practices changed, but I see there is a still a difference of opinion. I see this article for: https://grosser.it/2015/08/14/check-in-your-gemfile-lock/ and a few articles against.

Is it possible to add an option to run `bundle` and add the Gemfile.lock before the commit?

thanks,
Ankur

**Comment by PikachuEXE** [comment]
I don't think this gem is for automating every release related task
You got a custom workflow, you can try to automate it
Maybe `gem bump --no-commit && bundle && git commit (forgot arguments) && gem release --tag --push`?

**Comment by amalagaura** [comment]
Thank you, I'll adjust accordingly.
